apiVersion: v1
kind: Service
metadata:
  name: discovery-server
  labels:
    app: discovery-server
spec:
  selector:
    app: discovery-server
  ports:
    - port: {{ .Values.discoveryServer.service.port }}
      targetPort: {{ .Values.discoveryServer.service.port }}
  type: {{ .Values.discoveryServer.service.type }}

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: discovery-server
spec:
  replicas: {{ .Values.discoveryServer.replicaCount }}
  selector:
    matchLabels:
      app: discovery-server
  template:
    metadata:
      labels:
        app: discovery-server
    spec:
      containers:
      - name: discovery-server
        image: "{{ .Values.discoveryServer.image.repository }}:{{ .Values.discoveryServer.image.tag }}"
        ports:
        - containerPort: {{ .Values.discoveryServer.service.port }}
        
        env:
        - name: SPRING_CLOUD_CONFIG_URI
          value: http://config-server:8888
  
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: {{ .Values.discoveryServer.service.port}}
          initialDelaySeconds: 30
          periodSeconds: 10

        livenessProbe:
          httpGet:
            path: /actuator/health
            port: {{ .Values.discoveryServer.service.port}}
          initialDelaySeconds: 60
          periodSeconds: 15  

