apiVersion: v1
kind: Service
metadata:
  name: genai-service
spec:
  selector:
    app: genai-service
  ports:
    - port: {{ .Values.genaiService.service.port }}
      targetPort: {{ .Values.genaiService.service.port }}
  type: {{ .Values.genaiService.service.type }}

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: genai-service
spec:
  replicas: {{ .Values.genaiService.replicaCount }}
  selector:
    matchLabels:
      app: genai-service
  template:
    metadata:
      labels:
        app: genai-service
    spec:
      containers:
      - name: genai-service
        image: "{{ .Values.genaiService.image.repository }}:{{ .Values.genaiService.image.tag }}"
        ports:
        - containerPort: {{ .Values.genaiService.service.port }}

        readinessProbe:
          httpGet:
            path: /actuator/health
            port: {{ .Values.genaiService.service.port }}
          initialDelaySeconds: 30
          periodSeconds: 10

        livenessProbe:
          httpGet:
            path: /actuator/health
            port: {{ .Values.genaiService.service.port }}
          initialDelaySeconds: 60
          periodSeconds: 15
