apiVersion: apps/v1
kind: Deployment
metadata:
  name: vets-service
  namespace: petclinic
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vets-service
  template:
    metadata:
      labels:
        app: vets-service
    spec:
      imagePullSecrets:
      - name: acr-secret
      containers:
      - name: vets-service
        image: petclinic11acr.azurecr.io/spring-petclinic-vets-service:latest
        env:
        - name: SPRING_CONFIG_IMPORT
          value: "configserver:http://config-server:8888"
        - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
          value: "http://discovery-server:8761/eureka/"
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8083
          initialDelaySeconds: 30
